#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v21
# autospec commit: 5424026
#
Name     : R-rworldmap
Version  : 1.3.8
Release  : 1
URL      : https://ftp.osuosl.org/pub/cran//src/contrib/rworldmap_1.3-8.tar.gz
Source0  : https://ftp.osuosl.org/pub/cran//src/contrib/rworldmap_1.3-8.tar.gz
Summary  : Mapping Global Data
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-fields
Requires: R-raster
Requires: R-sp
Requires: R-terra
BuildRequires : R-fields
BuildRequires : R-raster
BuildRequires : R-sp
BuildRequires : R-terra
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
[![Travis-CI Build Status](https://app.travis-ci.com/AndySouth/rworldmap)](https://app.travis-ci.com/AndySouth/rworldmap)
[![rstudio mirror downloads](http://cranlogs.r-pkg.org/badges/grand-total/rworldmap)](https://github.com/r-hub/cranlogs.app)
[![rstudio mirror downloads](https://github.com/r-hub/cranlogs.app)](https://github.com/r-hub/cranlogs.app)
[![Research software impact](http://depsy.org/api/package/cran/rworldmap/badge.svg)](http://depsy.org/package/r/rworldmap)

%prep
%setup -q -n rworldmap

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1732159031

%install
export SOURCE_DATE_EPOCH=1732159031
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/rworldmap/CITATION
/usr/lib64/R/library/rworldmap/DESCRIPTION
/usr/lib64/R/library/rworldmap/INDEX
/usr/lib64/R/library/rworldmap/Meta/Rd.rds
/usr/lib64/R/library/rworldmap/Meta/data.rds
/usr/lib64/R/library/rworldmap/Meta/features.rds
/usr/lib64/R/library/rworldmap/Meta/hsearch.rds
/usr/lib64/R/library/rworldmap/Meta/links.rds
/usr/lib64/R/library/rworldmap/Meta/nsInfo.rds
/usr/lib64/R/library/rworldmap/Meta/package.rds
/usr/lib64/R/library/rworldmap/Meta/vignette.rds
/usr/lib64/R/library/rworldmap/NAMESPACE
/usr/lib64/R/library/rworldmap/R/rworldmap
/usr/lib64/R/library/rworldmap/R/rworldmap.rdb
/usr/lib64/R/library/rworldmap/R/rworldmap.rdx
/usr/lib64/R/library/rworldmap/data/Rdata.rdb
/usr/lib64/R/library/rworldmap/data/Rdata.rds
/usr/lib64/R/library/rworldmap/data/Rdata.rdx
/usr/lib64/R/library/rworldmap/doc/index.html
/usr/lib64/R/library/rworldmap/doc/rworldmap.R
/usr/lib64/R/library/rworldmap/doc/rworldmap.pdf
/usr/lib64/R/library/rworldmap/doc/rworldmap.rnw
/usr/lib64/R/library/rworldmap/doc/rworldmapFAQ.R
/usr/lib64/R/library/rworldmap/doc/rworldmapFAQ.Rnw
/usr/lib64/R/library/rworldmap/doc/rworldmapFAQ.pdf
/usr/lib64/R/library/rworldmap/help/AnIndex
/usr/lib64/R/library/rworldmap/help/aliases.rds
/usr/lib64/R/library/rworldmap/help/paths.rds
/usr/lib64/R/library/rworldmap/help/rworldmap.rdb
/usr/lib64/R/library/rworldmap/help/rworldmap.rdx
/usr/lib64/R/library/rworldmap/html/00Index.html
/usr/lib64/R/library/rworldmap/html/R.css
